In [1]:
import numpy as np

array = np.zeros(10)
array[4] = 1
print(array)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [2]:
array = np.arange(10, 50)
print(array)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [3]:
reversed_array = array[::-1]
print(reversed_array)


[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [4]:
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [5]:
array = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(array)[0]
print(non_zero_indices)

[0 1 4]


In [6]:
identity_matrix = np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
random_matrix = np.random.random((3, 3))
min_value = random_matrix.min()
max_value = random_matrix.max()

print(f"Minimum value: {min_value}")
print(f"Maximum value: {max_value}")


Minimum value: 0.017599066444161537
Maximum value: 0.9896446774969024


In [10]:
random_matrix = np.random.random((5, 5))
normalized_matrix = (random_matrix - random_matrix.min()) / (random_matrix.max() - random_matrix.min())
print(normalized_matrix)

[[0.10182501 0.98600581 0.76865978 0.06062474 0.64465746]
 [0.9755706  0.13786673 1.         0.88694703 0.1917897 ]
 [0.08075838 0.11145136 0.73682905 0.35482748 0.46321417]
 [0.0743603  0.59281108 0.26745215 0.49514387 0.33250062]
 [0.55796322 0.02893078 0.         0.71844478 0.61595402]]


In [11]:
array = np.array([1, 3, 5, 11, 15, 20, 25])
target = 14
closest_value = array[np.abs(array - target).argmin()]
print(closest_value)

15


In [12]:
array = np.array([[5, 9, 3], [10, 2, 15], [6, 7, 8]])
array[array.argmax(axis=1), np.arange(array.shape[1])] = 0
print(array)

[[ 5  9  3]
 [ 0  2 15]
 [ 6  0  0]]


In [13]:
array = np.array([2, 3, 2, 5, 8, 3, 3, 7, 2, 3, 5, 5, 5, 5])
unique, counts = np.unique(array, return_counts=True)
most_common_value = unique[np.argmax(counts)]
print(most_common_value)

5


In [14]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_product = np.dot(array, array.T)
print(matrix_product)


[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]


In [15]:
matrix = np.array([[6, 1, 1], [4, -2, 5], [2, 8, 7]])
determinant = np.linalg.det(matrix)
print(determinant)

-306.0


In [16]:
matrix = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])

try:
    inverse_matrix = np.linalg.inv(matrix)
    print(inverse_matrix)
except np.linalg.LinAlgError:
    print("Matrix is singular and cannot be inverted.")


[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]
